export const portfolioLinks = [
  {
    id: 1,
    color: "from-red-300 to-blue-300",
    title: "product design for vivian serum",
    desc: "one of my favorite projects that i made using blender 3d and photoshop for the final touch",
    img: "https://cdnb.artstation.com/p/assets/images/images/066/948/555/large/mohammx-ar-vivian-2-4.jpg?1694163031",
    link: "https://www.artstation.com/artwork/GeVqvB",
  },
  {
    id: 2,
    color: "from-blue-300 to-violet-300",
    title: "gmc hummer",
    desc: "i made it for a client long time ago took me about 2 weeks",
    img: "https://cdnb.artstation.com/p/assets/images/images/067/027/457/large/mohammx-ar-555555555555555.jpg?1694377407",
    link: "https://www.artstation.com/artwork/Al5ngW",
  },
  {
    id: 3,
    color: "from-violet-300 to-purple-300",
    title: "cyber lock",
    desc: "Futuristic lock based on Cyberpunk 2077",
    img: "https://cdna.artstation.com/p/assets/images/images/053/934/940/large/mohammx-ar-cyberlock.jpg?1663354629",
    link: "https://www.artstation.com/artwork/9NnNvQ",
  },
  {
    id: 4,
    color: "from-purple-300 to-red-300",
    title: "melted idea",
    desc: "made using blender",
    img: "https://cdna.artstation.com/p/assets/images/images/067/027/092/large/mohammx-ar-f22681560.jpg?1694376333",
    link: "https://www.artstation.com/artwork/8bLVPn",
  },
  {
    id: 5,
    color: "from-purple-300 to-red-300",
    title: "rocket s1 car",
    desc: "rocket s1 a project made by me using blender 3d",
    img: "https://cdna.artstation.com/p/assets/images/images/067/024/678/large/mohammx-ar-desert-1-1.jpg?1694370531",
    link: "https://www.artstation.com/artwork/vDRd2d",
  },
  {
    id: 6,
    color: "from-purple-300 to-red-300",
    title: "even the stone hearts bleed",
    desc: "even the stone hearts bleed one of my favorite art piece that i made using blender",
    img: "https://cdna.artstation.com/p/assets/images/images/067/027/710/large/mohammx-ar-sowrd-in-the-heart2.jpg?1694378051",
    link: "https://www.artstation.com/artwork/BXJLez",
  },
  {
    id: 7,
    color: "from-purple-300 to-red-300",
    title: "",
    desc: "",
    img: "",
    link: "",
  },
];
